### ISSUE TITLE
Standardise editable forms

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#145]
# Issue

All the catalogue item detail views (plus others) tend to display two states for information:

1. The "read-only" version, where information is readable and presented
2. The "editable" version, which replaces the read-only version with form controls to modify the information

A similar issue also arises with tabular data, where rows of a table may be able to be edited inline before saving and viewing the read-only version.

The current approach to doing this is to copy/paste similar code but modified per catalogue item domain type to match what is required. Each component then has to track what state the component is in - editing or not - plus what was the original data to reset to if cancelled, replacing the original data with the new saved data if committed, etc.

There are also the `mdm-ui` common controls which partly know about editable forms and use some key properties, yet are not very clear due to lack of TypeScript types defined on any of them.

The "copy/paste" approach has created a lot of duplication and possible deviation between styles. This issue should therefore discuss attempting to standardise these editable forms as much as possible.

# Suggestion 1

One suggestion can be found in PR #141 in the `editable-forms.ts` file:

* A `FormState<T, F>` object can be used to track common state such as `isEditing`, also:
  * Contain the `original` data
  * Store the form information with the currently "in edit" values
* The `FormState` is then able to standardise the following:
  * `start()` editing the form
  * `cancel()` editing the form (including resetting back to `original`)
  * `finish()` editing the form (including committing the changes to state)
  * `reset()` back to a known object state
  * Each action also allows observers to watch for when these occur

This approach also tries to use Angular [Reactive Forms](https://angular.io/guide/reactive-forms) to not try and re-invent the wheel with regards to form control tracking, validation, etc.

# Discussion

* Identify ways to standardise these editable forms, including updating `mdm-ui` common controls to support them
* What views should use editable forms and which are too simple to use them?
* What common controls need updating?
* Are there other approaches/suggestions to solve this?

**Comment by pjmonks** [comment]
After some discussion between myself and @gammonpeter we came up with the possible idea of re-using the same (or similar) read/edit experience used with the profiles.

# Background

For any model/container, by clicking on the "Default Profile" option, the core data is either read-only or editable inline. For a custom profile though, the data is read-only on the main screen, yet editable in a custom form in a modal dialog. This second approach seems to have some benefits:

1. It's clearer to the user that the current mode of operation has switched between "read" and "edit", and vice versa.
2. Each component view only has to worry about one mode of operation instead of two
3. Tracking global edit state (e.g. "are you sure you want to navigate away?" warning) is easier when wrapped up in the confines of an open or closed dialog.

# Suggestion 2

Instead of having any kind of "editable form" as is currently implemented, the approach could instead be:

* Use the existing dynamic profile dialog to render the required form for a default profile i.e. aliases, author, organisation, description and classifications. Or,
* Make a new, similar dialog for the purpose of displaying the default profile for editing.
* The same approach can be taken for the "Edit Description" and "Edit Title" options for editing catalogue items.

The benefits of this approach are:

1. This removes this issue of tracking read/write state completely, there is now a clear distinction between components as to their purpose.
2. This also adds more consistency for the user experience, as the default profile now functions exactly the same as any other profile.
3. Simplifies all the detail component views further still.

# Next Steps

Discuss with @jamesrwelch  if this UI approach would be suitable before continuing further.

**Comment by jamesrwelch** [comment]
@pjmonks @gammonpeter Yes, happy with turning inline edits into modal dialogs, as long as we can check the editing controls are sensible on a smaller browser.  The first iteration of "Metadata Catalogue" was built without any modal dialogs as a styling choice, but very happy to go the other way now - especially if it simplifies the code base.
