### ISSUE TITLE
Replace Terminology / CodeSet selector

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#156]
In a codeset, when adding a new term from a terminology, and when selecting a model for a model reference data type, there's a search-as-you-type dropdown which currently doesn't work - perhaps due to pagination issues.
It might be better to replace these (and any similar) with the same tree-view model selector that's used in other places.

An added bonus would be that if you're choosing a term for a codeset, it auto-selects the terminology that other terms are taken from.

**Comment by pjmonks** [comment]
@jamesrwelch For a start I have fixed the current implementation, the search was failing due to incorrect parameters being sent. Is this enough, or would you prefer the UI to change as requested?
