### ISSUE TITLE
Model Reference Data Types not showing

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#157]
The Data Type field is blank when a model reference type is displayed - see screenshot for one that points at a Terminology
![Screenshot 2021-06-02 at 14 21 27](https://user-images.githubusercontent.com/1869668/120487378-d4177e00-c3ad-11eb-8193-763bbea7008c.png)

The JSON coming through is:
```json
            "dataType": {
                "id": "802daee3-3a30-41b0-8651-53d90cff2207",
                "domainType": "ModelDataType",
                "label": "Admission Method",
                "model": "6e1d4447-cafc-40e3-9ace-940ee529866a",
                "breadcrumbs": [
                    {
                        ...
                    }
                ],
                "modelResourceId": "15ec0990-6fea-4f05-8c86-137f8c15f82e",
                "modelResourceDomainType": "uk.ac.ox.softeng.maurodatamapper.terminology.Terminology"
            }

```
@olliefreeman should `modelResourceDomainType` just be `Terminology`?

**Comment by pjmonks** [comment]
@jamesrwelch I don't have an example of a `ModelDataType` type and can't see how I can create one in the UI. Do you have an example or a way for me to replicate?

**Comment by jamesrwelch** [comment]
@pjmonks Create a new data element, while doing that, create a new data type that points at a terminology, codeset or reference data model - they're all implemented in the same way - as a ModelDataType

**Comment by pjmonks** [comment]
@jamesrwelch I'm having trouble replicating these steps, I can't seem to create a Terminology/Code Set/Reference Data type. This is my request:

```http
http://localhost:8080/api/dataModels/451f5897-ee55-41ac-97b9-49ed25b45bef/dataTypes

{
    "label": "Test Type",
    "description": "",
    "organisation": "",
    "domainType": "TerminologyType",
    "referenceDataType": {
        "id": ""
    },
    "referenceClass": {
        "id": ""
    },
    "terminology": {
        "id": "62ff5306-7aef-4a81-ad15-338db7cc1165"
    },
    "classifiers": [],
    "enumerationValues": [],
    "metadata": []
}
```

But I get a 422 response back:

```http
{
    "total": 1,
    "errors": [
        {
            "message": "Cannot bind DataType with unknown domainType [TerminologyType]"
        }
    ]
}
```

**Comment by jamesrwelch** [comment]
Ok, it looks like this has been updated, and the JSON should now look like:

**Comment by olliefreeman** [comment]
organisation was never needed.
and yes this was updated ages back when we introduced it, 
as to the original question yes it should just be `Terminology` .. i'll need to check why you're getting the FQDN

**Comment by olliefreeman** [comment]
it should def only be the simple name,
also you cant create ModelDataTypes to other DataModels at the moment...i cant remember why we made this choice

**Comment by olliefreeman** [comment]
i dont actally know where you got the FQDN from i cant see it being set like that anywheere in the code

**Comment by jamesrwelch** [comment]
Ok, confirmed that the FQDN was the fault of my importer.  I've fixed that, so yes, `modelResourceDomainType` is coming back as `Terminology` and `modelResourceId` is needed too.
