### ISSUE TITLE
Profile picture not obvious on profile editing screen

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#179]
When a user edits their profile for the first time, when no profile picture is set, it's really not obvious that you can do that (see screenshot).  Slightly better presentation needed so users can see what's going on.
![Screenshot 2021-06-14 at 13 57 59](https://user-images.githubusercontent.com/1869668/121896072-d0beb380-cd18-11eb-94fe-a7a24c3d2def.png)

**Comment by pjmonks** [comment]
@jamesrwelch - I've updated the profile page to improve the profile image editing experience. The main issue was that the default profile image is actually a transparent PNG, it looks nice from the navbar with the dark blue background but is impossible to see when the background is white.

Here are screenshots of what it looks like now:

![image](https://user-images.githubusercontent.com/3219480/122021823-f5b93200-cdbd-11eb-9b79-fee966f5864b.png)

![image](https://user-images.githubusercontent.com/3219480/122021921-09fd2f00-cdbe-11eb-82df-6b4823a2da5a.png)

Note that the documentation page https://maurodatamapper.github.io/user-guides/user-profile/user-profile/ will need updating as well to cover these UI changes.

**Comment by jamesrwelch** [comment]
Looks perfect, thanks! :). If you can send an updated screenshot to @GemmaHatton then she'll be able to update the documentation.
