### ISSUE TITLE
Select appropriate icons for lower level catalogue items

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#181]
![image](https://user-images.githubusercontent.com/3219480/121899641-84757280-cd1c-11eb-9260-ec7e1541e32c.png)

Icons were chosen for Data Type and Data Class (see above) to have a consistent icon set when used with the model tree. The icons to be used though are up for debate. For instance, is the chosen Data Class icon above too similar to Versioned Folders?

@jamesrwelch , @olliefreeman, @gammonpeter  - any icon can be chosen to substitute, so long as they from the [free Font-Awesome list](https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free)

**Comment by jamesrwelch** [comment]
How about 'section' or 'puzzle piece'?

**Comment by pjmonks** [comment]
![image](https://user-images.githubusercontent.com/3219480/121917209-cf978180-cd2c-11eb-8a1c-a79f9f9aaa1e.png)

![image](https://user-images.githubusercontent.com/3219480/121917388-fa81d580-cd2c-11eb-9923-339500c5f632.png)

Some options I've experimented with:

* Data class - `fa-puzzle-piece`
* Data type - `fa-code`
* Data element - `fa-atom`
* Term - `fa-bookmark`

@jamesrwelch  - any thoughts?

**Comment by pjmonks** [comment]
@jamesrwelch Have you had a chance to review these yet?

**Comment by jamesrwelch** [comment]
@pjmonks I'm not quite sure about `fa-code` for Data Type.  But can't find any better suggestions.  I like the others :) Very happy to go ahead with this!
