### ISSUE TITLE
Could not merge Documentation and Main Models 

### ISSUE THREAD

**Issue by theresanoble** [MauroDataMapper/mdm-ui#200]
**Describe the bug**
 Could not merge documentation and main models because of the JSON attached:

```
   "status": 400,
    "reason": "Bad Request",
    "errorCode": "TIS01",
    "message": "Container retrieval for container [DataModel] with no supporting service",
    "path": "/api/tree/dataModels/d8f2098e-5db1-4125-ab75-fbacf1fac9f6",
    "devMode": false,
    "version": "4.6.0"
}
 ```

Running Version 4.6 BE and 6.2 FE

**Comment by olliefreeman** [comment]
@pjmonks this old endpoint you're usiing is an abuse of the container endpoint and i thought you guys had updated it after i gave the new endpoint.

if you want the fully expanded tree for a model then the endpoint is

`api/tree/full/$modelUrlDomainType/$modelId`

e.g.
`/api/tree/full/dataModels/d8f2098e-5db1-4125-ab75-fbacf1fac9f6`

if you just after the top level contents of the model then the url is (and has always been)

`api/tree/$containerUrlDomainType/${catalogueItemUrlDomainType}/$catalogueItemId`
e.g.
`/api/tree/folders/dataModels/d8f2098e-5db1-4125-ab75-fbacf1fac9f6`

the container type is always needed to know which service to use to build the context from.

you should never have been able to use the endpoint you used lol

**Comment by pjmonks** [comment]
Fix has been applied first to MauroDataMapper/mdm-resources#23, once accepted the UI can be updated to use it.
