### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by gammonpeter** [MauroDataMapper/mdm-ui#224]
We are starting to see dependency issues related to our angular version. We should look at updating angular to the latest version to resolve these

**Comment by pjmonks** [comment]
Although not set in stone, if looking at past Angular releases from https://angular.io/guide/releases#support-policy-and-schedule, we can assume that v13 of Angular is due sometime in November 2021.

These resources should help with the upgrade process:

* https://angular.io/guide/updating - Keeping up to date
* https://update.angular.io/ - Builds a dynamic checklist of things to do for the upgrade process between major versions

**Comment by olliefreeman** [comment]
Renamed to angular 12 as that is the version we have got working
