### ISSUE TITLE
Enhancement suggestion: bulk view and edit of profile elements

### ISSUE THREAD

**Issue by aaronforshaw** [MauroDataMapper/mdm-ui#233]
When a user wishes to view or edit the value of a profile property against a Data Element, they can take the following path:

- Click on Data Model
- Click on Schema tab and click on relevant Data Class
- Click on the Elements tab
- Click on the relevant Data Element
- Select the relevant profile from a dropdown
- View and edit the profile values for the selected Data Element

It would be good if users could:
1. get to the profile values with fewer clicks
2. see and edit the profile values for multiple data elements in one place.

An example of (2) would be a tabular edit/display with Data Elements as rows and profile attributes as columns. How to deal with several Data Elements having different profiles would need some more thought.

**Comment by pjmonks** [comment]
In terms of navigating to the Data Elements faster, perhaps they could appear in the model tree view? Data Models already expand to Data Classes, so adding Data Elements would be one more level down, unless that is deemed to make the tree too cluttered - it all depends on how many Data Classes/Elements could appear.

I would agree though that getting to the Data Elements is cumbersome, a better way could be thought up.

**Comment by JenDaub** [comment]
Hi all, the bulk_edit.pdf does look as we imagined we would want to edit. The most important aspect is that we can see the data elements and their attributes in a grid view and from there select what to edit. At present our attributes are added to a single dynamic profile and we have ~13 attributes (fields). We would want to be able to see the attribute we were editing in context of the other attributes for that element as per the screen shots in bulk_edit.pdf.  The attribute values which are mainly Y/N etc only make sense in relation to each other.
