### ISSUE TITLE
Importing terminology fails in 4.7 version

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#236]
Importing sample terminology file failed. I've used a sample terminology file provided in Zulip chat. It was working OK in the past. See [file]( https://maurodatamapper.zulipchat.com/user_uploads/33927/Yia5bav3nbBII83nQG9cf2i6/terminology_3.1.xsd), and versioning info below.

            MDM_APPLICATION_COMMIT: 4.7.0
            MDM_UI_COMMIT: 6.3.1
            ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-csv:3.+;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-excel:3.+;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database:3.+;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-sqlserver:3.+"
            MDM_UI_THEME_NAME: "default"

**Comment by olliefreeman** [comment]
as an FYI you dont need `uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database:3.+` its a dependency of other plugins which is auto brought in.

1. what is the file you're trying to import? 
2. what importer are you using?
3. what is the error response you're getting?

if no useful info apparent from the UI then you can open the developer console in a web browser (using "inspect element") then choose the "network" tab and retry, the XHR filter will provide the API call made and then JSON response from the API, if you provide the body of the response this can help us work out why the import isnt working

**Comment by jelenadreskai** [comment]
I was using XML importer, so the XSD file was imported as an XML. And this was working in the past, if my memory is giving up on me.

Thanks for the comment about the plugin, I'll fix that/

Here is the error message. 
![image](https://user-images.githubusercontent.com/81437684/125530911-c1e046b1-e867-4dd8-a42b-70079d9e3c00.png)

**Comment by olliefreeman** [comment]
HI @jelenadreskai, so the terminology XSD you have provides the [XML schema document](https://www.w3schools.com/xml/schema_intro.asp) to create an XML file containing a  terminology which can be imported. 

This XSD will never have imported as it doesnt match the required format for the XML importer, which is why the error message from the logs states that no terminology was found to be imported.

**Comment by olliefreeman** [comment]
Closing as this is not an issue
