### ISSUE TITLE
Cannot add a DataType of type ReferenceDataModel

### ISSUE THREAD

**Issue by aaronforshaw** [MauroDataMapper/mdm-ui#241]
**Describe the bug**
An error is raised when trying to add a new Data Element with a Data Type of Reference Data Model. 

**To Reproduce**
Using the bootstrapped development data:
1. Go to Complex Test DataModel
2. Click on emptyclass
3. Add a new Data Element
4. For the Data Type, add a new type of Reference Data Model, pointing to the Simple Reference Data Model. Like this:

![Screenshot 2021-07-16 at 09 22 28](https://user-images.githubusercontent.com/20016570/125918749-f7a02a90-10d4-4e47-afec-3c1c3d8073a5.png)

5. Press the Submit Data Element button
6. Observe an error ```Cannot bind DataType with unknown domainType [ReferenceDataModelType]```

**Expected behavior**
Expect the save to be successful. This has worked previously.

**More info**
Inspecting the POSTed json:
```
{"label":"RefDataType","description":"","organisation":"","domainType":"ReferenceDataModelType","referenceDataType":{"id":""},"referenceClass":{"id":""},"terminology":{"id":"26f0c694-bb0d-48ab-b19f-f0ec5f2c7d0b"},"classifiers":[],"enumerationValues":[],"metadata":[]}
```
the domainType is set to ```ReferenceDataModelType```, but the backend I think expects ```ModelDataType```. If I use postman to change that I get further, but not all the way:
```
{
    "total": 2,
    "errors": [
        {
            "message": "Property [modelResourceDomainType] of class [class uk.ac.ox.softeng.maurodatamapper.datamodel.item.datatype.ModelDataType] cannot be null"
        },
        {
            "message": "Property [modelResourceId] of class [class uk.ac.ox.softeng.maurodatamapper.datamodel.item.datatype.ModelDataType] cannot be null"
        }
    ]
}
```

Also notice that my ReferenceDataModel.id of 6f0c694-bb0d-48ab-b19f-f0ec5f2c7d0b has been put into a terminology ID property.

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - Observed using develop branches of mdm-core, mdm-resources, mdm-ui
 - Observed using BE 4.7.0 FE 6.3.1

**Comment by pjmonks** [comment]
This looks related (or at least seems to be alongside) issue #157
