### ISSUE TITLE
Cannot change the type of a Data Element to Enumeration

### ISSUE THREAD

**Issue by aaronforshaw** [MauroDataMapper/mdm-ui#244]
**Describe the bug**
When trying to change the Data Type of a Data Element from e.g. an int to Enumeration, console errors are raised and the Data Element is not saved.

**To Reproduce**
Using the bootstrapped Simple Data Model:
1. Go to the simple Data Class in the Simple Data Model
2. Click on Elements
3. Add a Data Element, creating a Primitive int type while you do so
4. See that the Data Element is correctly saved to the Data Class
5. Select the Data Element you just created and click 'Edit'
6. An 'Edit Default Profile' modal is opened
7. In the Data Type section of the modal click 'Add a new Data Type'
8. Enter a label and description for the new Data Type, and select 'Enumeration' from the Type drop down
9. Add some Enumerations e.g. Key1/Val1 and Key2/Val2
10. Note various errors in the browser console e.g. ```TypeError: undefined is not an object (evaluating 'this.allRecords.forEach')```
11. Press Save and see a console error ```TypeError: undefined is not an object (evaluating 'item.value.enumerationValues.length')``` and see that the changes are not saved

**Expected behavior**
On pressing the Save button, the updated details should be saved

**Desktop (please complete the following information):**
 - MacOS
 - Safari
- Observed using develop branches of mdm-core, mdm-resources, mdm-ui
- Observed using BE 4.7.0 FE 6.3.1

**Comment by olliefreeman** [comment]
@gammonpeter im super confused about the state of this ticket, i thought you merged in a piece of work with a timeout, and yet #362 is still open and this branch is still open.
