### ISSUE TITLE
Cannot change permissions on a finalised model

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#245]
**Describe the bug**
The 'Add Group' button does not appear on the permissions modal window when viewing a finalised model.
I believe any changes to the 'publicly readable' and 'readable by authenticated users' are also not persisted.

**Expected Behaviour**
You should be able to change the permissions of a finalised model.

**Comment by pjmonks** [comment]
For comparison, here is what the group permissions looks like for a draft data model:

![image](https://user-images.githubusercontent.com/3219480/127142538-752c873a-4676-447e-b1f6-ef512f7dc4ff.png)

This is what it looks like for a finalised one:

![image](https://user-images.githubusercontent.com/3219480/127142595-716be9ee-148e-4c36-be3a-5e5d759227e9.png)

So the "Add Group" button is definitely missing and should be put back somehow.
