### ISSUE TITLE
Favourites not showing with illuminated favourite icon

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-ui#249]
**Describe the bug**
The favourite icon is shown in its non-illuminated state even when a model is in the user's favourite list.

**To Reproduce**
Add an item to the favourite list

**Expected behavior**
The favourite "star" is expected to be illuminated (Golden) for a model in the favourite list

**Screenshots**
![image](https://user-images.githubusercontent.com/27196895/127153118-7994eeea-b7c6-43a3-9a10-e7fda7917583.png)

**Comment by pjmonks** [comment]
This issue now has a fix waiting for review. Alongside this, I have also updated the interactivity of the favourites change events, for example if adding/removing a favourite then the tree view and favourites list will update automatically to show the new state.
