### ISSUE TITLE
Issues with Public Versioned Folders

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#258]
I've got a versioned folder which I've set to be publicly readable.  When not logged in, I cannot click on the versioned folder in the tree.  And I get a lot of (seemingly unrelated) 404 errors when I try to click on a DataModel that's contained in the VersionedFolder.  Might be related to https://github.com/MauroDataMapper/mdm-core/issues/125

**Comment by pjmonks** [comment]
The problem was the Versioned Folder page route was not added to the "allow" list for anonymous users. This is something that is often missed, so I'll add a related issue for longer term, but current fix in place resolves this.
