### ISSUE TITLE
The jodit configuration in angular.json seems to have no effect.

### ISSUE THREAD

**Issue by atpw25** [MauroDataMapper/mdm-ui#316]
The `jodit-editor` component from `jodit-angular` package seem to work with or without this configuration in `angular.json`. Maybe it should be removed?

```
...
"styles": [
    "src/styles.scss",
    "node_modules/jodit/build/jodit.min.css"
],
"scripts": [
    "node_modules/jodit/build/jodit.min.js"
],
...
```

**Comment by pjmonks** [comment]
@abwilson23 also found another issue with the Jodit editor when switching to full screen. As this is separate, issue #453 was created to tackle separately.
