### ISSUE TITLE
Admin OIDC ui doesn't handle non-root deployed instances

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-ui#322]
**The bug**
The OIDC connect redirect URL does not include the subfolder, such as https://mydomain.com/nhsd-test/

The result is that the apache server gives a generic 404 error

**Comment by olliefreeman** [comment]
Renamed as sub folder in mdm is a different thing to urls

**Comment by olliefreeman** [comment]
I suspect we need to use the site.url property to build the url

**Comment by pjmonks** [comment]
Initiated a hotfix branch to release this fix to 6.6.1.

**Comment by pjmonks** [comment]
This hotfix is now tagged in `main` branch under tag `6.6.1`.
