### ISSUE TITLE
User full official email address is displayed when a comment is made

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-ui#327]
**Describe the bug**
When a user made a comment on Mauro, the full user official email address is displayed on the comment section which might be in breach of user security. 
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to 'Mauro'
![email id](https://user-images.githubusercontent.com/87768436/135120100-6441ff56-e6aa-4ec3-9cf1-223ce2c51fa1.PNG)

2.	Click on 'a Model 
3.	Select the <Annotations> Menu 
4.	Keep Focus on the <Comments> menu from the dropdown down menu list
5.	Select <Add Comment> CTA
6.	Fill the required fields (Title and Description)
7.	Select the <Submit comment> CTA
8.	Verify the details of the user on the page
**Expected behaviour**
The user should have a unique identity rather than displaying the full official email address.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olliefreeman** [comment]
we should update the UI to display the above new field rather than use createdBy

also NHSD will need to add the following to their build.yml or runtime.yml
```yml
grails:
    views:
        excludeFields:
            - createdBy
```

**Comment by Jayafo** [comment]
Passed Retest
