### ISSUE TITLE
Deleted classifier is still displaying on the list 

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-ui#337]
**Describe the bug**
When a user deletes a classifier, the deleted classifier is still displaying on the list and when focused server error message is displayed. 
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to 'Mauro'
2.	Click on 'a Classifications menu
3.	Delete a classifier 
![Deleted Classifier](https://user-images.githubusercontent.com/87768436/135446240-bdc57c51-c98f-4354-b708-946822362515.PNG)

4.	The deleted classifier is still displaying on the list. 
**Expected behaviour**
The deleted classifier should not be on the list as it is expected to disappear online/realtime 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pjmonks** [comment]
The issue is that the Classification list is not responding to the event of the classifier being deleted. A full page reload shows that the classifier has been removed though.

**Comment by Jayafo** [comment]
Passed Retest
