### ISSUE TITLE
The Link Suggestion functionality is not suggesting any option when linking a Data Asset  

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-ui#355]
**Describe the bug**
When a user uses the Link suggestion functionality to link a Data Asset, no option is displaying when the Suggestion CTA is selected.  
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to 'Mauro'
2.	Select a **model** 
3.	Select a **sub folder** 
4.	Select the **Data Asset** in the view tree 
5.	Select the **Context** menu 
6.	Select Links in the dropdown menu list 
7.	Select **Link Suggestions** 
8.	A new page is open (Not sure if this is the process) 
9.	Select a Target Data Model 
10.	And select **Suggest** CTA 
11.	No option is displaying 
 
Expected behaviour
There should be option in the source data Element  

**Screenshots**
![image](https://user-images.githubusercontent.com/87768436/136577775-2263bc2b-f12a-4dc9-a86c-2007f23f9e90.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olliefreeman** [comment]
@Jayafo the link suggestions are based off some analysis of the elements...as this looks like the 2 datamodels have different names and you prove that there are links which should be suggested...

the analysis is done by comparing data element names, its entirely possible there are no links to suggest.

I would suggest having 2 models which are almost identical where you know there are dataelements with the same name and datatype label this should produce a definite suggesiton

**Comment by olliefreeman** [comment]
if you can provide a list of the content in each datamodel and prove that you believe there should be suggested links then we would consider this a bug

**Comment by jamesrwelch** [comment]
@olliefreeman The screenshot suggests that something is not working - usually you'd expect to see a list of Data Elements down the left-hand side, with empty drop-downs on the right-hand side.

**Comment by Jayafo** [comment]
Hello @jamesrwelch for the input and @olliefreeman please can you review @jamesrwelch comment above. Thanks

**Comment by jamesrwelch** [comment]
I cannot reproduce this - Can you confirm that your source data model has data elements?
