### ISSUE TITLE
The Add CTA on Link Suggestion functionality is not enabled when linking a Data Asset

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-ui#370]
**Describe the bug**
When a user uses the Link suggestion functionality to link a Data Asset, the **Add** CTA is not enabled with Target Data Element option displaying  **No Suggestions**! 
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to 'Mauro'
2.	Select a model
3.	Select a sub folder
4.	Select the Data Asset in the view tree
5.	Select the Context menu
6.	Select Links in the dropdown menu list
7.	Select Link Suggestions
8.	A new page is open (Not sure if this is the process)
9.	Select a Target Data Model
10.	And select Suggest CTA
11.	Suggested links are populated 
12.	The Add CTA is not enabled 

**Expected behaviour**
The Add CTA should be enabled 

**Screenshots**
![image](https://user-images.githubusercontent.com/87768436/138129309-0fd93afb-ab47-488d-904e-7188dfc02e0b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olliefreeman** [comment]
Also as per the other link suggestion ticket can you provide proof that you expect there to be links suggested, as this page simply shows it’s attempted link suggestions but for all the data elements there are no suggestions, which may well be because there’s no sensible suggestions 

Can you provide a screenshots of 2 elements too think should be linked

**Comment by jamesrwelch** [comment]
@Jayafo as Ollie says above, if there is not a source and target element selected to "Add", then it's completely correct for the "Add" button to be disabled.  Unless we're not understanding your issue, I recommend this issue is closed.

**Comment by Jayafo** [comment]
Accepted explanation to close defect
