### ISSUE TITLE
Advanced Search does not work for public user

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#382]
1. Do not log in to Mauro. Look around using unauthenticated user.
2. Click on the Search
3. Click on Advanced option

Expected results:
Advanced search form shows up

Current behavior:
User sent to the main MDM page

--
MDM Release
UI: 6.6.0
CORE: 4.10.0

**Comment by jamesrwelch** [comment]
If you're able to get a PR in for this one by Wednesday, we'll be able to include it in the next release :)

**Comment by GBishop-PHSA** [comment]
Clicking the advanced search link when not logged in was resulting in a request of:
/api/tree/folders?queryStringParams=[object Object]
The queryStringParams should be expanded before sending the request, so it sends as:
/api/tree/folders?includeDocumentSuperseded=true&includeModelSuperseded=true&includeDeleted=true

**Comment by GBishop-PHSA** [comment]
@jamesrwelch The pull request is ready for review
