### ISSUE TITLE
Move built in issue reporting to open issues in GH not YT

### ISSUE THREAD

**Issue by olliefreeman** [MauroDataMapper/mdm-ui#386]
We need the UI to direct users to the following url https://github.com/MauroDataMapper/mdm-ui/issues/new/choose
to report issues rather than to the YT page.

This is because we want bugs all in one place.

**Comment by olliefreeman** [comment]
GH allows multiple types of templates and we can probably create one which automates nicely with MDM so the users are directly taken to the template issue rather than the "choose" page

**Comment by pjmonks** [comment]
@olliefreeman @jamesrwelch Some notes on me playing around on GitHub before going down any implementation route:

# Authentication

To add an issue to a GitHub repo you do have to be signed in as a GitHub user. It is possible to create an issue with the GitHub API, but I think this should be ruled out for two reasons:

1. You would need to capture the GH user's credentials somehow before sending the request, which I don't think we want to do.
2. The entire issue would be posted to the repo via the API request, so the full issue body would have to be assembled via the UI. Again, I don't think this is something that should be done by `mdm-ui`.

The alternative is to redirect straight to the repo (in a separate window/tab) via URL. I've tried this and if you are not signed in to GitHub you will be asked to do that first, then redirect back to the issue page e.g. https://github.com/MauroDataMapper/mdm-ui/issues/new/choose or a direct link to a specific issue template. This seems like the most sensible approach to take.

# Context information

The error screens (e.g. "Server error" page) contain context information, such as stacktraces, which are useful to transfer across to the issue. However, there is no simple way of doing this without manually constructing the issue body itself.

A simpler solution could be to have a "Copy to clipboard" button on the UI to copy (and nicely format) the details, then ask the user to paste it into the GitHub issue before submitting - this could be explained in the GH issue template text.

# Proposal

Based on this and discussions, I feel like the following could be implemented:

1. Add a feature toggle/environment switch to allow reporting of issues (default to "on")
2. Clicking on the "Report issue" link in the footer will redirect to the GitHub "choose new issue" page - authentication will be handled there
3. Clicking on the "Report issue" link in an error screen will take you directly to an issue page. Suggest creating a new issue template just for these kinds of errors (such as defining a new label like "system error", to differentiate from less severe bugs)
4. Implement a copy/format function for the error pages so they are suitable for pasting into GitHub issues
