### ISSUE TITLE
Email list in Admin page in wrong order

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#394]
The list of emails that appears in the admin pages currently appears ordered by date/time, in ascending order.  This is slightly inconvenient - ideally you'd like to see the most recently sent emails first.  The default, initial ordering should be swapped.

**Comment by mkim219** [comment]
Hi @jamesrwelch! Can I work on this issue?

**Comment by jamesrwelch** [comment]
@mkim219 By all means, yes - I've assigned to you.  Feel free to discuss anything here in this thread, or on our Zulip chat:  https://maurodatamapper.zulipchat.com/. Thanks!

**Comment by mkim219** [comment]
Hi @jamesrwelch. May I ask a few questions? 
1. In order to access admin, do I need to ask admin info? 
2. In order to fix this issue, should I link mdm-resource to mdm-ui?

**Comment by jamesrwelch** [comment]
I'll copy in @gammonpeter who's the UI expert here and may be able to give advice.  You'll need to fork the mdm-ui repo and create a new branch.  
I think you should be able to make the change required from within mdm-ui, so you won't need to update (and locally link) mdm-resources.

**Comment by mkim219** [comment]
Yes, I already forked mdm-ui repo and created a new branch. I wonder how do I get into admin page in order to fix this issue. I will talk @gammonpeter  more detail. Thanks for quick response!

**Comment by jamesrwelch** [comment]
Ah, ok, yes - if you're logged in as an admin user, there's an 'emails' link on the admin drop-down - see:  https://maurodatamapper.github.io/user-guides/admin-functionality/admin-functionality/ (The section about emails is not very complete at the moment!)
