### ISSUE TITLE
When editing profile details, enumeration values are not presented in the correct order

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#397]
I've defined a dynamic profile with an enumeration type.  When I edit instances of that profile, the drop-down menu presenting the options is not displaying the values in the correct order.

**Comment by GBishop-PHSA** [comment]
@jamesrwelch Is this a duplicate of https://github.com/MauroDataMapper/mdm-ui/issues/423?

**Comment by pjmonks** [comment]
I think @GBishop-PHSA is correct, this seems to be a duplicate of #423 which has already been fixed. I've checked myself with a custom profile and enumeration, and the display of the enumeration values is sorted correctly now.

![image](https://user-images.githubusercontent.com/3219480/159480192-a4d64b24-29ff-4f94-9cb1-46c2c9c8fc20.png)

I shall close this issue.
