### ISSUE TITLE
Bug in editing enumerations as part of new data type

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#398]
When using the 'new data element' wizard, and creating a new enumeration data type as part of that process.  After creating a couple of enumeration values, editing new enumeration values causes previously-created ones to vanish.

1. Create new data element
2. Choose to create a new data type
3. Select "Enumeration"
4. Add two enumeration values
5. Add a third, and start editing it

Result - first and second enumeration values disappear and are not saved

Using Safari, on a Mac

**Comment by pjmonks** [comment]
Cannot replicate this in the 7.3.0 release. I was able to start creating an enumeration type with at least 4 values:

![image](https://user-images.githubusercontent.com/3219480/221889559-70dcae65-3e99-4883-95f4-14b70911f89c.png)

Closing this issue as a result.
