### ISSUE TITLE
Create Internal link when editing html

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#417]
At the moment, you can create a link to another element when editing markdown, but not when editing html.
It would be good if the same functionality was available when editing in html
<img width="224" alt="Screenshot 2022-01-09 at 11 26 11" src="https://user-images.githubusercontent.com/1869668/148680274-d1b2d4d4-7bc6-4158-b33d-3115ba978920.png">
.

**Comment by pjmonks** [comment]
@jamesrwelch There is already this feature in the HTML editor, labelled "Add Element" in the editor toolbar:

![image](https://user-images.githubusercontent.com/3219480/148746896-6420ee6f-1d60-4e55-b4f2-21eaccb955c3.png)

It does look like it could be improved though:

1. The link created directly references the element by its UUID, whereas the Markdown version would generate a URL where the name was included. The HTML version should probably change to match, and then ensure that hard references to UUID do not exist.
2. I could also look to try and update the UI a bit, maybe change the toolbar button icon to look more consistent.

**Comment by jamesrwelch** [comment]
@pjmonks Yes, ok, sorry, I didn't see that.  The two definitely need unifying then :)
