### ISSUE TITLE
Classification list limited to 10 items [limitation]

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#430]
Open an existing datamodel
Select Default Profile
Click on Edit Default Profile
Select Classifiers drop down list
The list contains only 10 classifiers. 

Note: The same behavior is in the Advanced Search, where list of classifiers shows up. 

Expected: 
All public classifiers should be shown in the drop down list.

UI: 6.6.0
CORE: 4.10.0

@jamesrwelch @olliefreeman @pjmonks 
Our solution was to increase the limit to 100 (because we do not expect more than 100 classifiers). This was quick and easy. If you want this code change, assign it to Gail.

But perhaps, a different UI control could be introduced to type and search for classifier. Or perhaps make this configurable.

**Comment by pjmonks** [comment]
The dropdown list control seems to be missing the `all=true` parameter in the request.

Comparing the "Classification" list in the left side:

![image](https://user-images.githubusercontent.com/3219480/149557816-0fcf9f01-6c83-443e-b4ec-2923da0800e3.png)

```
GET http://localhost:8080/api/classifiers?all=true

Response:

{
  count: 14,
  items: [...]
}
```

But this is what the dropdown control does:

![image](https://user-images.githubusercontent.com/3219480/149557954-8c7c5b91-beb3-4171-aa80-415825549d89.png)

```
GET http://localhost:8080/api/classifiers

Response:

{
  count: 10,
  items: [...]
}
```

So by not providing the `all` query parameter, only the top 10 items are ever returned. This is easily fixed.
