### ISSUE TITLE
Email notifications use catalog URL, which sends users to the missing page

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#442]
1. Reset User password
2. Email generated points to the variable "catalog URL"
3. Look at the email queue of failed messages
4.  Failed message shows a pointer to the catalog
5. When user clicks on the URL, user is taken to the undefined webpage
(Example: http://www.test.com/undefined)

![image](https://user-images.githubusercontent.com/81437684/151086967-493002ba-24d1-4365-b6d7-36271632e474.png)
![image](https://user-images.githubusercontent.com/81437684/151086902-8c14abb9-da18-4eff-a41c-6d68af4bfca1.png)

Environment: Mauro baseline 4.10.0/6.6.0

**Comment by jelenadreskai** [comment]
It's a one line code change. Can be assigned to @GBishop-PHSA , she looked at it already.

**Comment by jamesrwelch** [comment]
@jelenadreskai @GBishop-PHSA I'm not sure I understand - is this just a case of needing to change the catalogue URL variable through the admin interface?  Or is something else going on?

**Comment by olliefreeman** [comment]
Yeah I agree, l this is actually a backend thing and is supposed to pull the info from
The api property site_url

**Comment by jamesrwelch** [comment]
Ok, I see.  I guess the email log should really show the actual text sent, with the property values replaced?

**Comment by olliefreeman** [comment]
@jamesrwelch  ??? the email log is the email exactly as its sent to the user stored into the DB. Therefore the property replacement has already been done.

**Comment by jamesrwelch** [comment]
Ok, having looked at the API response and the UI rendering of the Url, I understand now.  Yes, @GBishop-PHSA please do fix this for us :)

**Comment by GBishop-PHSA** [comment]
@jamesrwelch Ready for review. This change affects any text displayed in Mauro that contains a url (eg. Data Model HTML descriptions, email history).
