### ISSUE TITLE
Links to emails don't work correctly in email logs

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#446]
In the admin interface, in the email logs, email addresses appear as links, but when clicked go to 'undefined'. 
<img width="497" alt="Screenshot 2022-01-26 at 21 24 00" src="https://user-images.githubusercontent.com/1869668/151249463-40e0edd3-5f4b-4b16-93c4-9b25abf5c933.png">
Similar to #445 / #442, and so assigning to Gail, but I realise that's a bit presumptuous, so please feel free to unassign!

**Comment by GBishop-PHSA** [comment]
@jamesrwelch  Ready for review.
