### ISSUE TITLE
Sorting and filtering of summary metadata

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-ui#458]
# Description

When viewing summary metadata in the UI, individual results display as expected however they are listed in an arbitrary order and ordering and filtering based on the 'Name' does not work.

# Steps to reproduce

- Import example data model with summary metadata as JSON by using JSON DataModel Importer in UI: [example-summary-metadata.json.txt](https://github.com/MauroDataMapper/mdm-ui/files/7988462/example-summary-metadata.json.txt) _(may need to remove .txt extension)_
- Open the imported data model and select either of the imported data classes.
- Select the Data tab in the UI.
- Attempt to sort by Name by clicking on arrow or filter by clicking on filter icon.

# Expected behavior

- Filtering and sorting summary metadata by name should be possible.

# Screenshots

Example of attempt to filter by name:
<img width="640" alt="Screen Shot 2022-02-02 at 16 50 14" src="https://user-images.githubusercontent.com/33897179/152199269-46722b62-213b-4753-b316-7d35d0d2ae87.png">
explain your problem.

# Environment

## Desktop 

Please complete the following information:
- OS: macOS
- Browser: Chrome 97

# Additional context

Tested using latest develop of mdm-core, mdm-ui, mdm-resources.

**Comment by pjmonks** [comment]
This bug is actually because the endpoints for fetching the summary metadata list do not support filtering and sorting. I have created MauroDataMapper/mdm-core#389 to be completed first before this issue can be fixed.
