### ISSUE TITLE
Incorrect URL used for rebuilding indexes

### ISSUE THREAD

**Issue by olliefreeman** [MauroDataMapper/mdm-ui#461]
The backend API updated the url from `api/admin/rebuildLuceneIndexes` to `api/admin/rebuildHibernateSearchIndexes` and forgot to tell the UI.

Please update accordingly.

**Comment by jon-bowen** [comment]
The tweak needed to be made in mdm-resources. Have tested with mdm-ui using the "npm link" mechanism. No change required to mdm-ui.

**Comment by jon-bowen** [comment]
PR @ https://github.com/MauroDataMapper/mdm-resources/pull/47
Added npm commands "clean-windows" and "build-windows" using "del", as the "rm" command isn't understood by powershell.

**Comment by pjmonks** [comment]
I've approved and merged https://github.com/MauroDataMapper/mdm-resources/pull/47. Since there are no other changes to this issue from the UI, I can close this now as fixed.
