### ISSUE TITLE
 HTML Editor does not parse the URL link properly

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#474]
# Description
HTML Editor does not parse the URL link properly.

# Steps to reproduce
1. Edit Description of the data model.
2. Add a link in the description
Markup: [GitHub Pages](https://pages.github.com/)
Or simply: https://pages.github.com/

# Behavior
The URL gets changed: http://localhost:8083/undefined

# Expected behavior
The correct URL is open.

# Environment
UI: 7.0 CORE: 5.0

See related item (Gail has fixed this in the previous release) for email:
https://github.com/MauroDataMapper/mdm-ui/issues/442

**Comment by abwilson23** [comment]
Did some testing and was unable to reliably replicate the error. 

1. Pasting one of the supplied links into the description of a data model, saving, and then clicking on it worked fine for 2 data models. 
2. For a 3rd, I was redirected to the undefined page.
