### ISSUE TITLE
Previous model versions are not displayed in folders in tree

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-ui#490]
# Description

When viewing folder contents in the tree in the left-hand pane, only the latest model versions are displayed. Previous model versions should also be accessible.

# Steps to reproduce

1. In a folder, create a model, finalise it (creating version 1.0.0), create a new version of the model, finalise again (creating version 2.0.0).
2. Only the version 2.0.0 of the finalised model is displayed in the tree

# Expected behavior

The user should be able to access previous model versions in the tree view. My thinking from brief discussions is:

- An option should be added to the 'Filters' icon at the top of the tree along with 'Show deleted models' to 'Show superseded models'.
- The default for 'Show superseded models' should be ~true~.  false

@jamesrwelch, would you be able to comment on the above?

The appropriate parameter to pass to the tree endpoints is `includeModelSuperseded=false`.

# Environment

## Desktop 

Please complete the following information:
- OS: macOS
- Browser: Chrome 99
- Mauro: latest develop of core, ui and resources.

**Comment by jamesrwelch** [comment]
I think adding this as another option is a good idea.  Is this just about models marked as superseded, or any old version?

**Comment by joe-crawford** [comment]
:+1: The backend refers to any model with a finalised new model version as superseded, so it's all of those models.

**Comment by olliefreeman** [comment]
we want to put the tick/check box choice back into the UI, which should sit alongside the "include deleted models". It should default to false.

**Comment by pjmonks** [comment]
This looks related to #279 .
