### ISSUE TITLE
Create landing page for new Catalogue Search

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#524]
# Description

The new Catalogue Search functionality will start with a landing page that does not initiate any search, but provides all the necessary options to start. Below are some mockups of what it may look like:

![image](https://user-images.githubusercontent.com/3219480/167451087-ac1add93-8d89-49b4-bfa0-f734be53355f.png)

![image](https://user-images.githubusercontent.com/3219480/167450902-bbb47e3a-0da7-4fad-83b5-9a169e110f77.png)

# Features

1. The landing page is full width across the page - it does not split between two views like the Browse pages do.
2. Initially only a wide search bar will be present. An expandable/collapsable section will allow the user to toggle viewing the more advanced filter options
3. The existing search filters will be present in the advanced section, but will use a better UI layout.
4. Only when the Search button is clicked will a new search start, which will navigate to the new `CatalogueSearchListingComponent`

**Comment by OButlerOcc** [comment]
Addition: default label only search. option for full search, currently the opposite but now prohibitive due to load
