### ISSUE TITLE
Cyclical dependency when installing @angular-devkit/build-angular

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#553]
# Description

It is not possible to install all NPM package dependencies with `--strict-peer-deps`, which is an issue because the Renovatebot will use that to install all dependencies cleanly. There appears to be a cyclical dependency error when resolving the package `@angular-devkit/build-angular`.

# Steps to reproduce

1. Clone a clean copy of `mdm-ui`
2. Delete your local copy of the `package-lock.json` file
3. Delete the `node_modules` folder if it exists
4. Run `npm uninstall @angular/localize` and `npm uninstall @angular/language-service` - these are no needed, and uninstalling them will remove other resolution errors.
5. Now run `npm install --strict-peer-deps` to ensure all peer dependencies are valid.

# Expected behavior

`npm install ` should complete successfully without any errors.

# Additional context

Below is a copy of the resolution report that npm produces:
[eresolve-report.txt](https://github.com/MauroDataMapper/mdm-ui/files/8799214/eresolve-report.txt)

**Comment by jamesrwelch** [comment]
@pjmonks I believe this has now resolved itself - are you able to check?  It would be nice to get some of our dependencies updated, and it looks as though the packages have sorted themselves out now.

**Comment by pjmonks** [comment]
@jamesrwelch I'm not entirely convinced it's working but something has definitely changed now. First I rebased one of the renovate PRs, specifically #540 . After some retries on Jenkins, it now successfully builds to completion. There are other issues with the PR though to do with an artifact file though - is there a way to reset RenovateBot and start again clean perhaps?

As for running the steps in this issue though, I still get dependency issues but at least I see a new list of problems now:

```
# npm resolution error report

2022-12-07T10:58:00.883Z

While resolving: mdm-ui@7.3.0-SNAPSHOT
Found: @angular/animations@12.2.13
node_modules/@angular/animations
  @angular/animations@"12.2.13" from the root project

Could not resolve dependency:
peer @angular/animations@"^14.2.12" from jodit-angular@1.14.2
node_modules/jodit-angular
  jodit-angular@"^1.12.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --no-strict-peer-deps, --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@angular/animations",
    "version": "12.2.13",
    "whileInstalling": {
      "name": "mdm-ui",
      "version": "7.3.0-SNAPSHOT",
      "path": "C:\\Code\\Mauro\\MauroDataMapper\\mdm-ui-deps"
    },
    "location": "node_modules/@angular/animations",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "@angular/animations",
        "spec": "12.2.13",
        "from": {
          "location": "C:\\Code\\Mauro\\MauroDataMapper\\mdm-ui-deps"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "@angular/animations",
    "spec": "12.2.13",
    "from": {
      "location": "C:\\Code\\Mauro\\MauroDataMapper\\mdm-ui-deps"
    }
  },
  "edge": {
    "type": "peer",
    "name": "@angular/animations",
    "spec": "^14.2.12",
    "error": "INVALID",
    "from": {
      "name": "jodit-angular",
      "version": "1.14.2",
      "whileInstalling": {
        "name": "mdm-ui",
        "version": "7.3.0-SNAPSHOT",
        "path": "C:\\Code\\Mauro\\MauroDataMapper\\mdm-ui-deps"
      },
      "location": "node_modules/jodit-angular",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "jodit-angular",
          "spec": "^1.12.3",
          "from": {
            "location": "C:\\Code\\Mauro\\MauroDataMapper\\mdm-ui-deps"
          }
        }
      ]
    }
  },
  "strictPeerDeps": true,
  "force": false
}
```

This list of issues is different than originally discussed. This part...

```
Could not resolve dependency:
peer @angular/animations@"^14.2.12" from jodit-angular@1.14.2
node_modules/jodit-angular
  jodit-angular@"^1.12.3" from the root project
```

Means that the latest version of `jodit-angular` was used and that has a peer dependency to Angular 14. You mentioned to me that you were working on an upgrade path to Angular 14, perhaps the way to fix all of these issues is a mass upgrade? To verify, you would need to do a clean install of node modules using the `npm install --strict-peer-deps` command, that should be the same as what RenovateBot does.
