### ISSUE TITLE
Next iteration of spreadsheet-style bulk editor

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#576]
The first iteration of the bulk editor tool provides a grid-based view to edit the profile fields of selected Data Elements from a Data Model.  This Epic defines some tasks for the next iteration of this functionality - improving its usability and making it more applicable across the rest of Mauro.  There's one ticket for each task, but these may need to be broken down into sub-epics if necessary

# Tasks

- [x] #577
- [x] #578
- [x] #579
- [x] #580
- [x] #581
- [x] #582
- [x] #583
- [x] #584
- [x] #585

# Related

- MauroDataMapper/docs#63

**Comment by pjmonks** [comment]
All tasks have been completed in this epic now.
