### ISSUE TITLE
Include the 'default' profile in the options for the profile to be edited

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#578]
# Overview

The current bulk-editor only supports profiles defined by a profile service - it would be nice if we could also include the 'default profile' as an option.  This may need to be hand-coded, but bulk-editing descriptions will be an important use-case.

<img width="1184" alt="Screenshot 2022-06-30 at 14 42 31" src="https://user-images.githubusercontent.com/1869668/176692538-35eff64d-b0e9-4077-be28-1484b48c971c.png">

# Tasks

- [x] #590
- [x] #591
- [x] #592

**Comment by pjmonks** [comment]
A "default profile" does not exist as such, but there may be ways to pretend or intercept that idea using profiles, but treated differently.

* If handled in the back-end, it may require extensive implementation to intercept a special profile and map the properties to their hardcoded catalogue item properties.
* Alternatively, the front-end could treat this as a profile in it's own right for display/editing, but would have to handle the read/write operations manually by mapping the catalogue item properties to/from the profile.

However, if it could be treated like any other profile, then the bulk editor should just work by adding additional tabs to the existing edit interface.

Things to consider though:

1. The "default profile" will differ slightly between domain types e.g. a Data Class and Data Element may have slightly different core metadata properties.
2. A plan will need to be made as to how to implement the profile interception (most likely in the front-end).

**Comment by pjmonks** [comment]
All issues (sub-tasks) under this main task have now been completed/merged, this issue can also be closed now.
