### ISSUE TITLE
Make the grid full-screen

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#579]
The bulk editor is one of those components that requires as much screen-space as it can get.  Making it full screen - either as a modal dialog, or with a separate SPA route, would make the tool a lot more usable.  
Bear in mind the subsequent point in this epic about the HTML / MD editor - #585

<img width="1768" alt="Screenshot 2022-06-30 at 14 45 36" src="https://user-images.githubusercontent.com/1869668/176693252-ac60e99d-e35a-42fd-a88a-110de9ff48b3.png">

**Comment by jamesrwelch** [comment]
I'm thinking of something close to a 'Google Sheets' experience, if that's a useful reference point.

**Comment by pjmonks** [comment]
This should be quite simple to achieve. The UI Router organises routes and child components in a hierarchical structure, and the main browse window uses a parent root called `appContainer.mainApp.twoSidePanel.catalogue`. This splits the page into two - the left always shows the model tree, the right always shows what the specific URL wants to show e.g. data model selected.

To make the bulk edit page full width, just change this route to `appContainer.mainApp.bulkEdit`, then test the resulting layout and adjust as necessary.

**Comment by pjmonks** [comment]
@jamesrwelch As an aside, would it be worth making any editor screen full-width? I'm thinking about when an item is edited in the singular, currently a very large dialog pops up with the edit components, but would it flow better if navigated to a full-width page instead?
