### ISSUE TITLE
Show the paths of the elements in the grid

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#580]
The current bulk editor displays the column names, but it's not clear of the context of each of these - in particular where there may be multiple DEs in different DCs with the same name.  
On solution might be to find a way of including the breadcrumbs, or a rendering of them, in the boxes.  Alternatively, a view based on the tree view so that DEs in the same DC are grouped as part of a hierarchy.

<img width="355" alt="Screenshot 2022-06-30 at 14 47 42" src="https://user-images.githubusercontent.com/1869668/176693676-8fda4871-9938-4b55-9244-7460c5e60726.png">

**Comment by pjmonks** [comment]
Paths can be determined through item breadcrumbs - there may even be services available to convert breadcrumbs into paths, but rendering a breadcrumb array shouldn't be difficult.

The main thing to check would be if the `AgGrid` component can custom render cells. If so, the cell containing the item label would then need to render the breadcrumb too, but nicely and not squashed.

**Comment by aaronforshaw** [comment]
See https://github.com/MauroDataMapper/mdm-core/pull/340 for a backend enhancement.

**Comment by pjmonks** [comment]
`mdm-core` should now be updated to include the necessary breadcrumbs, so work can continue on this issue.
