### ISSUE TITLE
Make the bulk editor work at the Data Class level

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#582]
At the moment, you can only bulk-edit from the Data Model Level.  It would be nice if you could do the same thing at the DC level - to select from the DEs contained within that DC (and its contained classes).
This may reduce the priority of #577 .

**Comment by pjmonks** [comment]
It would be worth checking first if `mdm-core` can support bulk edit of profiles for items that are not Data Elements. As far as I have understood it, it should be possible but needs to be tested. I've applied the "backend needed" label for now to have this verified before any further work starts.

**Comment by aaronforshaw** [comment]
PR https://github.com/MauroDataMapper/mdm-core/pull/331 adds backend tests which verify that the existing bulk editing endpoints do work for editing profiles on data types and data classes. I think no other backend changes are required for this issue; although the use case is to make the bulk editor at the Data Class level, the UI will still use the endpoints which are secured by data model ID.

**Comment by pjmonks** [comment]
This has been completed whilst I worked on #594. As the UI was changed to support different domain types, I tested that the backend changes worked as expected.
