### ISSUE TITLE
Make the bulk-editor tool work for terms in a terminology or a codeset

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#583]
At the moment, the bulk editor only works for DEs within a DM.  It would be nice if we can get it working for Terms within a Terminology, and within a CodeSet

**Comment by pjmonks** [comment]
It would be worth checking first if `mdm-core` can support bulk edit of profiles for items that are not Data Elements. As far as I have understood it, it should be possible but needs to be tested. I've applied the "backend needed" label for now to have this verified before any further work starts.

**Comment by aaronforshaw** [comment]
Please see https://github.com/MauroDataMapper/mdm-core/issues/329 which describes the backend verification.

**Comment by pjmonks** [comment]
This has been completed whilst I worked on #594. As the UI was changed to support different domain types, I tested that the backend changes worked as expected.
