### ISSUE TITLE
Make the bulk-editor work on data classes, data types.

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#584]
At the moment the bulk editor only works for DEs within a DC.  It would be nice if we could also edit DCs or DTs within a DM (perhaps in separate screens, rather than all together, if that's an easier starting point).

**Comment by pjmonks** [comment]
It would be worth checking first if `mdm-core` can support bulk edit of profiles for items that are not Data Elements. As far as I have understood it, it should be possible but needs to be tested. I've applied the "backend needed" label for now to have this verified before any further work starts.

**Comment by aaronforshaw** [comment]
PR https://github.com/MauroDataMapper/mdm-core/pull/331 adds backend tests which verify that the existing bulk editing endpoints do work for editing the profiles on data classes and data types.

**Comment by pjmonks** [comment]
This has been completed whilst I worked on #594. As the UI was changed to support different domain types, I tested that the backend changes worked as expected.
