### ISSUE TITLE
Expand 'Favourites'

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#588]
If an item in the 'favourites' view was a folder, or a model, it would be nice if it could be expanded the way it would be if it was in the tree view.  At the moment, for example, if you have a favourite folder, you can see its details, but have to go back to the tree view to see its contents.

This would make the 'favourites' tab a nice way to have a clean tree view to work from.

**Comment by pjmonks** [comment]
At the moment the Favourites panel is a list control, it sounds like this would be converted into a tree view, with each top-level node being one of the favourite catalogue items. Expanding the node would be similar to the Models tree view where child items would then be populated.

Or, as an alternative design, what if the Favourites list panel were removed entirely and the Models tree was used instead? To make that work:

1. The existing models tree view already highlights favourites with a star icon
2. A new filter could be added to the control to "Show favourites", reducing the nodes down to only those starred.
3. The Model tree then already has the capability to expand/collapse items.

I'm not sure which UX approach might be nicer for the user - @jamesrwelch , any thoughts?

**Comment by jamesrwelch** [comment]
@pjmonks There are some items that you can favourite - elements, classifiers, some terms - that don't appear in the regular tree.  So keeping it as a separate tab might be best.  For those we can expend, we offer the option; for those that can't we keep them a single items.  
Bear in mind that this may be a component we'd want to re-use as part of a dashboard we present when a user first logs on - if that makes any difference at this stage.  (We don't need to do any major re-architecting right now)

**Comment by jamesrwelch** [comment]
I think the search field is a lower priority - it's hopefully unlikely that someone will have so many favourites that they need to search within them. I like the idea of the additional UI controls - or right-click options.
