### ISSUE TITLE
External References not being copyed when creating a new version

### ISSUE THREAD

**Issue by pringinacio** [MauroDataMapper/mdm-ui#593]
# Description

Having a _Model_ with one or more _Data Classes_, where at least on _Data Class_ has a _Data Element_ that is an _External Reference_, when creating a _New Version_ of the model, the _External Reference_ _Data Elements_ disappear on the new version. The same happens on _Data Classes_ that has other _Data Classes_ as _External References.

# Steps to reproduce

1. Have a **Finalized** Model (version _1.1.0_)

![image](https://user-images.githubusercontent.com/11587606/177502451-ba952c37-ad86-4fab-b660-932ae7474544.png)

2. Create a new version of the **Finalized** Model

![image](https://user-images.githubusercontent.com/11587606/177502658-7dde5db6-5cc2-463d-ad39-848d8f9e829e.png)

3. New version (main) does not contain the _External Reference_

![image](https://user-images.githubusercontent.com/11587606/177502744-a07f19fb-2a01-4df5-9cbf-ff483541b6c8.png)

# Expected behavior

The new version should maintain the _External References_

# Environment

- Mauro Version: 7.1.0
- mdm-core Version: 5.1.0

**Comment by jamesrwelch** [comment]
Hi @pringinacio , Thank you very much for reporting this issue.  It looks as though it may be the same as https://github.com/MauroDataMapper/mdm-core/issues/242 ?  In which case, it has been fixed and will be part of the next release. Please let me know if you think otherwise and we can take a closer look :)

**Comment by pringinacio** [comment]
@jamesrwelch it appears to be the same problem (if VF is a Versioned Folder). If it is then this issue is a duplicate of [242](https://github.com/MauroDataMapper/mdm-core/issues/242)
