### ISSUE TITLE
`mat-progress-spinner` component jumps in safari

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#608]
In safari on a Mac, the `<mat-progress-spinner>` component jumps around and looks very unappealing.  This might be a styling issue, or maybe we need a new component.  Will try and upload a video to demonstrate if I can work out how.

**Comment by jamesrwelch** [comment]
This may just be an issue when the browser zoom is not 100%.  People with sensible eyesight, or sensible screens, may not have the same problem.

**Comment by jamesrwelch** [comment]
This fix sounds like the right one, and after playing, can confirm that it's to do with the `transform-origin` setting

**Comment by jamesrwelch** [comment]
@pjmonks Yep, sorry, meant to link here:  https://github.com/angular/components/pull/23674.  We'll need to upgrade angular material components to get the fix, as far as I can see.

**Comment by pjmonks** [comment]
We'll need to identify which version of Angular Material to upgrade to. Our npm dependencies are a bit of a mess already, so don't want to drastically upgrade anything unless it's a patch version.

**Comment by jamesrwelch** [comment]
Completely agreed.  And we need to work out how to tidy up the existing dependency spaghetti in the near future.  We'll talk about the next release in the meeting tomorrow.
