### ISSUE TITLE
Bring in Idle Service

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#726]
We currently depend on the User Idle service here: https://github.com/rednez/angular-user-idle
This doesn't yet run on Angular 14, and will cause us dependency conflicts when we try to upgrade our dependencies.  Since the package only provides one service, and is MIT licensed, let's bring the files into our codebase for now, and reconsider in the future.

**Comment by pjmonks** [comment]
The `UserIdleService` was already integrated into the `mdm-explorer` repo, if you look here you can get the code needed to work: https://github.com/MauroDataMapper/mdm-explorer/blob/develop/src/app/external/user-idle.service.ts
