### ISSUE TITLE
no error issue in details when an error occurs

### ISSUE THREAD

**Issue by theresanoble** [MauroDataMapper/mdm-ui#81]
Describe the bug
 When branching a model, that took more then 30 mins, I received a server error. Used inspector to see timeout error, however there was no information in the details grid view.
'''Request
PUT /mauro-data-mapper/api/dataModels/73d373d5-8223-4fd0-86cb-e9a9acc8844b/newBranchModelVersion HTTP/1.1
Content-Type: application/json
Pragma: no-cache
Accept: application/json, text/plain, /
Accept-Language: en-gb
Accept-Encoding: gzip, deflate, br
Cache-Control: no-cache
Host: oxnetdwa02.oxnet.nhs.uk
Origin: https://oxnetdwa02.oxnet.nhs.uk
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
Referer: https://oxnetdwa02.oxnet.nhs.uk/mauro-data-mapper/
Content-Length: 30
Connection: keep-alive
Cookie: JSESSIONID=D924061337AF0D22E109CD931200B6CB; _ga=GA1.3.721931879.1620143590; _gid=GA1.3.1515164793.1620143590
Response
HTTP/1.1 504 Gateway Time-out
Date: Wed, 05 May 2021 10:15:29 GMT
Content-Type: text/html
Connection: keep-alive
Cache-Control: no-store, no-cache, must-revalidate
Content-Length: 192
Server: nginx/1.14.0 (Ubuntu)'''
![Screenshot 2021-05-05 at 11 29 35](https://user-images.githubusercontent.com/67739552/117128933-f5c51b80-ad95-11eb-8a91-98772058239f.png)

To Reproduce
Go to 'OUH instance'
Branch a large model - wait for it to receive a server error - open details, see that there is nothing there

Desktop (please complete the following information):

OS: Mac OS 11.3.1
Browser Safari
Version 14.1
Additional context
I've only tried this in the OUH instance, will test others when I get a chance.

**Comment by theresanoble** [comment]
I would also note that @olliefreeman confirmed that the branching was in fact successful, however there was notification of this on the front end. (not sure if this is a separate bug?)

**Comment by olliefreeman** [comment]
not an addle bug...the exception was a gateway timeout ... at which point the response has been issued...so the UI would never know that the model has branched....we may need to go async for the branching if the model is over a certain size
