### ISSUE TITLE
Links from the description field are not valid URLs

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#852]
# Description

When testing on the NHS Data Dictionary instance - https://modelcatalogue.cs.ox.ac.uk/nhsd-datadictionary/ - the hyperlinks in the description fields of an item are just the Mauro path, but are not valid URLs to redirect to.

# Steps to reproduce

Go to an item, like this: https://modelcatalogue.cs.ox.ac.uk/nhsd-datadictionary/#/catalogue/dataClass/6d054bbe-e634-45ee-837a-ed7f83c3f77c//15deb5ca-e327-4f5a-b240-eedfdd5e3fd3/description

Notice that the description field contains what looks like hyperlinks:

![image](https://github.com/MauroDataMapper/mdm-ui/assets/3219480/6d35cb67-fafd-4bbc-8a18-16fc3e532914)

However, copy the link address from any of these links e.g. "ACCOMODATION", and this is the exact `href` from the `<a>` tag:

```
dm:Classes and Attributes|dc:Classes|dc:ACCOMMODATION
```

Click on these links, and the browser will not know what to do.

# Expected behavior

These hyperlinks should be valid URLs to redirect to.

# Related Issues

The fix for this is related to these issues:

- [x] #860 
- [x] MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#11

**Comment by pjmonks** [comment]
I feel like I have worked on these links previous (perhaps with the Markdown editor, not the HTML version) - there may be existing PRs in this repo related to updates I worked on for hyperlinks, but we will need to locate them.

**Comment by jamesrwelch** [comment]
We certainly did some work in this space - it may be that the ingest / publication needs aligning with whatever works through the UI.  Definitely an issue to get sorted though

**Comment by pjmonks** [comment]
My initial testing shows that creating a hyperlink to a Mauro item manually through the UI works fine and generates a valid URL reference. The next step would be to inspect the DD ingest code like @jamesrwelch suggested, this is probably where the incorrect URLs are being generated.

**Comment by pjmonks** [comment]
Based on feedback about the ingest of the DD and links, I've created:

- #860 

This will keep links as paths but allow them to be displayed correctly.

**Comment by pjmonks** [comment]
I think this is now complete, closing this epic.
