### ISSUE TITLE
Merge a "main" branch into a separate branch of a model or versioned folder

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#854]
# Description

At the moment, you can only merge changes from a model/versioned folder from a new branch back into the "main" branch (draft) model/versioned folder, but you cannot do this the other way around. For example, in this scenario:

![image](https://github.com/MauroDataMapper/mdm-ui/assets/3219480/e21dda08-ebee-4734-965d-2eb6d50c0921)

- You can select the "Merge" option to merge branch "CR8000" to "main"
- You currently _cannot_ merge "main" to "CR8000"

The second case is important too because changes may have been made to "main" whilst the other branch has been idle or worked on, so the latest "main" changes should be able to be committed back to the other branch for consistency.

# Related

- NHSDigital/DataDictionaryPublication#198

**Comment by OButlerOcc** [comment]
Not a ui change, actually a security change see Pr: https://github.com/MauroDataMapper/mdm-core/pull/460

**Comment by OButlerOcc** [comment]
Reopened for a question, I can now merge a main Version Folder into other branches, Do I want to also be able to merge individual models inside? Security policies seems to indicate folder only but task is a tad ambigious on this

**Comment by jamesrwelch** [comment]
@OButlerOcc I would say it only really makes sense to merge whole VFs at a time - if you were to merge single models within a VF you'd likely end up with dangling links - references to things that didn't exist.

**Comment by pjmonks** [comment]
@OButlerOcc and @jamesrwelch - I think if I remember correctly, a merge diff is allowed on a standalone model so long as it is not inside a versioned folder - the VF takes precedence over sub-models within it. So a merge, either as `main -> branch`, or `branch -> main`, should apply to:

- Models (Data Model, Terminology, Code Sets etc) not inside a VF
- Versioned Folders
- But _not_ models inside a Versioned Folder
