### ISSUE TITLE
History tab missing on DataElements

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-ui#877]
# History tab missing

The User Interface for Data Elements does not enable the user to see the history of change for the data element.  The parent class history does not show the changes to elements on the classes either

# Suggested resolution

Implement a means to view the history

**Comment by joe-crawford** [comment]
Thanks for the report @oughnic, we should also make sure as part of the Micronaut work that the backend is recording the history in a consistent way for the different items.
