### ISSUE TITLE
Update dependencies based on security vulnerabilities

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#91]
Dependabot has noticed we have dependencies on versions of codemirror and loads libraries, which have security vulnerabilities.  We need to update these two dependencies to the latest version

More details here: https://github.com/MauroDataMapper/mdm-ui/security/dependabot

**Comment by jamesrwelch** [comment]
@pjmonks Ok, I think I've just given you access

**Comment by gammonpeter** [comment]
updated
